export default {
  login: "Alok07184",
  id: 65760708,
  node_id: "MDQ6VXNlcjY1NzYwNzA4",
  avatar_url: "https://avatars.githubusercontent.com/u/65760708?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Alok07184",
  html_url: "https://github.com/Alok07184",
  followers_url: "https://api.github.com/users/Alok07184/followers",
  following_url: "https://api.github.com/users/Alok07184/following{/other_user}",
  gists_url: "https://api.github.com/users/Alok07184/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Alok07184/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Alok07184/subscriptions",
  organizations_url: "https://api.github.com/users/Alok07184/orgs",
  repos_url: "https://api.github.com/users/Alok07184/repos",
  events_url: "https://api.github.com/users/Alok07184/events{/privacy}",
  received_events_url: "https://api.github.com/users/Alok07184/received_events",
  type: "User",
  site_admin: false,
  name: "Alok Ranjan Singh",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "B.Tech in Information and Technology,\r\nDid training in Ardent on Android Development.\r\nAlso 5 star coder at hackerrank, and a 3 star coder at codechef.\r\n",
  twitter_username: null,
  public_repos: 2,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-05-22T08:36:35Z",
  updated_at: "2022-05-09T09:35:59Z"
};
